-- Create a service account and its first usable credential in one transaction.
-- The RPC accepts only a digest and short display prefix; raw key material is
-- generated by the API, returned once by the API, and never reaches Postgres.

begin;

drop function if exists public.company_admin_create_service_account(
    uuid,uuid,uuid,text,text,text[],timestamptz,text
);
drop function if exists public.company_admin_create_service_account(
    uuid,uuid,uuid,text,text,text[],text,text,timestamptz,text
);
create function public.company_admin_create_service_account(
    p_organization_id uuid,
    p_actor_user_id uuid,
    p_service_account_id uuid,
    p_name text,
    p_environment text,
    p_scopes text[],
    p_key_hash text,
    p_key_prefix text,
    p_expires_at timestamptz,
    p_request_id text
) returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_actor_role text;
    v_account public.service_accounts%rowtype;
    v_billing_owner_id uuid;
    v_key_id uuid;
begin
    perform public.lock_company_admin_namespace(p_organization_id);
    v_actor_role := public.lock_company_actor_role(
        p_organization_id,p_actor_user_id);
    select billing_owner_id into v_billing_owner_id
      from public.organizations
     where id=p_organization_id
     for update;

    if v_actor_role not in ('company_owner','company_admin')
       or v_billing_owner_id is null
       or char_length(trim(p_name)) not between 1 and 100
       or p_environment !~ '^[A-Za-z0-9._-]{1,32}$'
       or cardinality(p_scopes) not between 1 and 12
       or not (p_scopes <@ array[
            'proxy:invoke','usage:write','usage:read_own','customer:route',
            'customer:auto_provision','customers:import','repositories:register',
            'installations:register','provider:read','provider:manage',
            'jobs:create','jobs:read','jobs:cancel']::text[])
       or p_key_hash !~ '^[0-9a-f]{64}$'
       or char_length(p_key_prefix) not between 4 and 16
       or p_expires_at is null
       or p_expires_at <= now()
       or p_expires_at > now()+interval '365 days'
       or (select count(*) from public.service_accounts
            where organization_id=p_organization_id and status='active'
              and (expires_at is null or expires_at>now())) >= 100 then
        perform public.append_company_audit(
            p_organization_id,p_actor_user_id::text,
            coalesce(v_actor_role,'none'),p_request_id,
            'service_account.create.denied','service_account',
            p_service_account_id::text,'denied');
        return jsonb_build_object(
            'ok',false,'code','forbidden_or_limit');
    end if;

    insert into public.service_accounts(
        id,organization_id,name,environment,scopes,created_by,expires_at
    ) values (
        p_service_account_id,p_organization_id,trim(p_name),p_environment,
        p_scopes,p_actor_user_id,p_expires_at
    ) returning * into v_account;

    insert into public.api_keys(
        key_hash,name,created,owner_id,organization_id,service_account_id,
        key_type,scopes,environment,key_prefix,expires_at,created_by
    ) values (
        p_key_hash,v_account.name,now(),v_billing_owner_id::text,
        p_organization_id,v_account.id,'organization_service',
        v_account.scopes,v_account.environment,p_key_prefix,
        v_account.expires_at,p_actor_user_id
    ) returning id into v_key_id;

    perform public.append_company_audit(
        p_organization_id,p_actor_user_id::text,v_actor_role,p_request_id,
        'service_account.created','service_account',v_account.id::text,
        'committed');
    return jsonb_build_object(
        'ok',true,'id',v_account.id,'name',v_account.name,
        'environment',v_account.environment,'scopes',v_account.scopes,
        'status',v_account.status,'expires_at',v_account.expires_at,
        'key_id',v_key_id,'prefix',p_key_prefix);
exception when unique_violation then
    -- PL/pgSQL rolls back both inserts before entering this handler. Persist a
    -- content-free denial without ever leaving a keyless service account.
    perform public.append_company_audit(
        p_organization_id,p_actor_user_id::text,
        coalesce(v_actor_role,'none'),p_request_id,
        'service_account.create.denied','service_account',
        p_service_account_id::text,'denied');
    return jsonb_build_object('ok',false,'code','duplicate');
end;
$$;
revoke all on function public.company_admin_create_service_account(
    uuid,uuid,uuid,text,text,text[],text,text,timestamptz,text
) from public, anon, authenticated;
grant execute on function public.company_admin_create_service_account(
    uuid,uuid,uuid,text,text,text[],text,text,timestamptz,text
) to service_role;

-- A replica on the previous API contract still sends the legacy eight
-- arguments. Keep that signature during the rollout, but fail closed: without
-- a key digest and one-time prefix it cannot satisfy the initial-key invariant.
create function public.company_admin_create_service_account(
    p_organization_id uuid,
    p_actor_user_id uuid,
    p_service_account_id uuid,
    p_name text,
    p_environment text,
    p_scopes text[],
    p_expires_at timestamptz,
    p_request_id text
) returns jsonb
language sql
security definer
set search_path = public, pg_temp
as $$
    select jsonb_build_object(
        'ok',false,
        'code','client_upgrade_required',
        'required_contract','initial_service_key'
    );
$$;
revoke all on function public.company_admin_create_service_account(
    uuid,uuid,uuid,text,text,text[],timestamptz,text
) from public, anon, authenticated;
grant execute on function public.company_admin_create_service_account(
    uuid,uuid,uuid,text,text,text[],timestamptz,text
) to service_role;

commit;
